[package]
name = "phenix-runtime-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.5"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }

[lib]
proc_macro = true
